# Aegis MemoryAgent — © 2026 Ben Duske. Licensed under the MIT License (see LICENSE).
"""Live end-to-end capability demo (Track 1) — the three claims, all proven at once.

Runs the REAL engine against Qwen Cloud (DashScope-compatible) and captures one
transcript that demonstrates every behaviour in docs/demo-script.md:

  1. CROSS-SESSION RECALL  teach facts/prefs, throw the agent away, rebuild a fresh
                           agent over the same on-disk store (NO history replay) —
                           it still knows you.
  2. BOUNDED RECALL        recall() packs ranked memory into a token budget, so the
                           prompt never overflows no matter how big memory grows —
                           we set a tiny budget and show low-salience items dropped
                           while used_tokens stays under the cap.
  3. FORGETTING            episodic memories whose salience decays below the floor are
                           pruned. Real decay+floor logic; only the *clock* is synthetic
                           (timestamps backdated to simulate elapsed days — labelled as
                           such in the transcript, since we can't wait two weeks live).

Run:  QWEN_API_KEY=sk-... python scripts/live_full_demo.py
Writes docs/transcripts/live-full-capability-demo.md and prints a summary.
NOT part of the keyless test suite (makes real Qwen Cloud calls).
"""
import os
import sys
import shutil
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))

from memoryagent import config  # noqa: E402
from memoryagent.agent import MemoryAgent  # noqa: E402
from memoryagent.memory import MemoryStore, _now, _approx_tokens  # noqa: E402

OUT = os.path.join(ROOT, "docs", "transcripts", "live-full-capability-demo.md")
DAY = 86400.0

lines = []  # transcript buffer


def emit(s=""):
    print(s)
    lines.append(s)


def section(title):
    emit()
    emit(f"## {title}")
    emit()


def main():
    if not config.QWEN_API_KEY:
        sys.exit("QWEN_API_KEY not set — this demo makes real Qwen Cloud calls.")

    store_dir = tempfile.mkdtemp(prefix="memoryagent-full-demo-")
    emit("# Aegis MemoryAgent — live end-to-end capability demo")
    emit()
    emit(f"- Engine: real Qwen Cloud — chat=`{config.CHAT_MODEL}` embed=`{config.EMBED_MODEL}`")
    emit(f"- Endpoint: `{config.QWEN_BASE_URL}`")
    emit(f"- Store: fresh temp dir (no pre-seeded memory)")
    emit("- This file is machine-generated by `scripts/live_full_demo.py`.")

    try:
        # ---- 1. teach over session 1 -------------------------------------
        section("1. Session 1 — teach the agent (real chat + memory extraction)")
        a1 = MemoryAgent(MemoryStore(store_dir))
        for u in [
            "Hi, I'm Ben. Always call me Ben, never 'Commander'.",
            "I run Northwind Labs, a privacy-first robotics startup in Lubbock, Texas.",
            "I'm allergic to peanuts — keep that in mind for any food suggestions.",
            "I prefer concise, direct answers with no fluff.",
        ]:
            emit(f"**you>**  {u}")
            emit(f"**aegis>** {a1.chat(u)}")
            emit()
        s1 = a1.mem.stats()
        emit(f"_after session 1: {s1['facts']} facts · {s1['episodes']} episodes · "
             f"{s1['prefs']} prefs on disk_")

        # ---- 2. cross-session recall after a restart ---------------------
        section("2. Restart — brand-new agent over the same store (no history replay)")
        a2 = MemoryAgent(MemoryStore(store_dir))
        emit(f"_memory loaded from disk: {a2.mem.stats()}_")
        emit()
        for q in [
            "What's my company and where is it based?",
            "Suggest a quick lunch — and what should you call me?",
        ]:
            emit(f"**you>**  {q}")
            emit(f"**aegis>** {a2.chat(q)}")
            emit()
        emit("_The fresh agent answered from disk-loaded memory alone — no prior "
             "turns were replayed into the prompt._")

        # ---- 3. bounded recall under a tiny token budget -----------------
        section("3. Bounded recall — memory packed into a token budget")
        store = a2.mem
        total_facts = len(store.facts)
        query = "Tell me about Ben and his work and health."
        tight = 24  # tokens — deliberately tiny to force the cap to bite
        picked, _prefs = store.recall(query, token_budget=tight)
        used = sum(_approx_tokens(p["text"]) for p in picked)
        emit(f"Query: _{query}_")
        emit(f"Token budget: **{tight}** · facts available on disk: **{total_facts}**")
        emit(f"Recalled **{len(picked)}** item(s), using **{used}** tokens "
             f"(≤ budget {tight}):")
        for p in picked:
            emit(f"  - ({_approx_tokens(p['text'])} tok) {p['text']}")
        emit()
        emit(f"_The remaining {total_facts - len(picked)} lower-salience fact(s) were "
             "left out: recall stays under budget no matter how large memory grows._")

        # ---- 4. forgetting via decayed salience --------------------------
        section("4. Forgetting — decayed episodic memories pruned below the floor")
        emit(f"_Decay half-life: {config.DECAY_HALFLIFE_DAYS}d · salience floor: "
             f"{config.SALIENCE_FLOOR}. To demo time-based decay in seconds, the "
             "timestamps below are **backdated** — the decay+floor maths is the real "
             "engine, only the clock is simulated._")
        emit()
        before = len(store.episodic)
        # Backdate three existing episodes far into the past so their decayed
        # salience drops under the floor; leave the rest recent.
        aged = 0
        for it in store.episodic[:3]:
            it["ts"] = _now() - 120 * DAY  # ~120 days old vs 14d half-life
            aged += 1
        emit(f"Episodes before: **{before}** "
             f"(backdated {aged} of them to ~120 days old)")
        dropped = store.forget()
        emit(f"`store.forget()` pruned **{dropped}** decayed episode(s); "
             f"**{len(store.episodic)}** recent one(s) survived.")
        emit()
        emit("_Recent, salient memories are kept; stale low-importance ones fall away — "
             "the store self-prunes instead of growing without bound._")

        # ---- summary -----------------------------------------------------
        section("Result")
        ok_recall = s1["facts"] > 0
        ok_bounded = used <= tight and len(picked) < total_facts
        ok_forget = dropped >= 1
        emit(f"- [{'x' if ok_recall else ' '}] cross-session recall — facts survived a restart")
        emit(f"- [{'x' if ok_bounded else ' '}] bounded recall — used {used} ≤ {tight} tok, "
             f"{len(picked)}/{total_facts} facts fit")
        emit(f"- [{'x' if ok_forget else ' '}] forgetting — {dropped} decayed episode(s) pruned")
        all_ok = ok_recall and ok_bounded and ok_forget

        os.makedirs(os.path.dirname(OUT), exist_ok=True)
        with open(OUT, "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")
        print(f"\nTranscript written: {OUT}")
        sys.exit(0 if all_ok else 1)
    finally:
        shutil.rmtree(store_dir, ignore_errors=True)


if __name__ == "__main__":
    main()
