# Aegis MemoryAgent — © 2026 Ben Duske. Licensed under the MIT License (see LICENSE).
"""Live HTTP-service deployment proof (Track 1).

Teaches the agent over ONE running uvicorn process, then FULLY RESTARTS the
service and recalls over a SECOND process pointed at the same on-disk MEMORY_DIR.
This proves the deployable face (app.py) preserves cross-session memory across a
real service restart — the guarantee a hosted Alibaba Cloud deployment must keep.

Run:  QWEN_API_KEY=sk-... python scripts/live_http_demo.py
It writes docs/transcripts/live-http-service-demo.md and prints a summary.
NOT part of the test suite (makes real Qwen Cloud calls); kept as a repro script.
"""
import json
import os
import shutil
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.request

PORT = int(os.environ.get("DEMO_PORT", "8077"))
BASE = f"http://127.0.0.1:{PORT}"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "transcripts", "live-http-service-demo.md")

log = []  # (kind, label, payload) for the transcript


def _req(method, path, body=None):
    url = BASE + path
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(url, data=data, method=method,
                                 headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=120) as r:
        return json.loads(r.read().decode())


def wait_healthz(timeout=40):
    end = time.time() + timeout
    while time.time() < end:
        try:
            return _req("GET", "/healthz")
        except (urllib.error.URLError, ConnectionError):
            time.sleep(0.5)
    raise SystemExit("server did not become healthy")


def start_server(memory_dir):
    env = dict(os.environ, MEMORY_DIR=memory_dir)
    return subprocess.Popen(
        [sys.executable, "-m", "uvicorn", "memoryagent.app:app",
         "--port", str(PORT), "--log-level", "warning"],
        cwd=os.path.join(ROOT, "src"), env=env,
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )


def stop_server(proc):
    proc.terminate()
    try:
        proc.wait(timeout=15)
    except subprocess.TimeoutExpired:
        proc.kill()


def main():
    if not os.environ.get("QWEN_API_KEY"):
        raise SystemExit("QWEN_API_KEY not set")
    memory_dir = tempfile.mkdtemp(prefix="memoryagent-http-")
    user = "ben"

    try:
        # ---- PROCESS #1: teach ---------------------------------------------
        p1 = start_server(memory_dir)
        try:
            hz = wait_healthz()
            log.append(("note", "PROCESS #1 healthz", hz))
            teach = [
                "Hi, I'm Ben. Always call me Ben, never 'Commander'.",
                "I run a company called Northwind Labs — a privacy-first robotics startup.",
                "I like concise, direct answers with no fluff.",
            ]
            for t in teach:
                out = _req("POST", "/chat", {"user": user, "text": t})
                log.append(("turn", t, out["reply"]))
            log.append(("note", "stats after teaching", _req("GET", f"/memory/{user}/stats")))
        finally:
            stop_server(p1)
        log.append(("event", "SERVICE RESTART", "process #1 stopped; process #2 starting on same MEMORY_DIR"))

        # ---- PROCESS #2: recall over the same store ------------------------
        p2 = start_server(memory_dir)
        try:
            hz2 = wait_healthz()
            log.append(("note", "PROCESS #2 healthz (fresh process)", hz2))
            ask = [
                "What's my company, and what's it about?",
                "What should you call me?",
            ]
            for q in ask:
                out = _req("POST", "/chat", {"user": user, "text": q})
                log.append(("turn", q, out["reply"]))
            # observable bounded recall
            rec = _req("GET", f"/memory/{user}/recall?q=company%20name&budget=400")
            log.append(("note", "bounded recall (q='company name', budget=400 tokens)", rec))
            # forget() = decayed-salience pruning (GC). On fresh data nothing is stale
            # yet, so dropped=0 is the expected, honest result.
            forg = _req("POST", f"/memory/{user}/forget")
            log.append(("note", "forget() — salience-based pruning (decay GC); 0 dropped on fresh data is expected", forg))
        finally:
            stop_server(p2)

        write_transcript(memory_dir)
        print("OK — transcript written to", OUT)
    finally:
        # Every run (success or failure) must clean up its temp MEMORY_DIR —
        # the transcript is written to OUT, not read back from here. Mirrors
        # scripts/live_full_demo.py's store_dir cleanup.
        shutil.rmtree(memory_dir, ignore_errors=True)


def write_transcript(memory_dir):
    lines = [
        "# Live HTTP-service deployment proof — real Qwen Cloud",
        "",
        "Generated by `scripts/live_http_demo.py` against the live Qwen Cloud API.",
        "It teaches the agent over one uvicorn process, **fully restarts the service**,",
        "then recalls over a second process pointed at the same on-disk `MEMORY_DIR`.",
        "",
        f"- **Endpoint:** {os.environ.get('QWEN_BASE_URL', 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1')}",
        "- **What it proves:** the deployable FastAPI face (`app.py`) keeps cross-session",
        "  memory across a real process restart — recall is backed by the persistent store,",
        "  not by in-process conversation state. Mount `MEMORY_DIR` on a volume and the",
        "  guarantee holds across container restarts (see DEPLOY.md).",
        "- **Reproduce:** `QWEN_API_KEY=sk-... python scripts/live_http_demo.py` (key never committed).",
        "",
        "```text",
    ]
    for kind, label, payload in log:
        if kind == "turn":
            lines.append(f"POST /chat  you>  {label}")
            lines.append(f"            aegis> {payload}")
            lines.append("")
        elif kind == "event":
            lines.append("")
            lines.append(f"=== {label} ===")
            lines.append(f"    ({payload})")
            lines.append("")
        else:
            lines.append(f"# {label}:")
            lines.append("  " + json.dumps(payload, ensure_ascii=False))
            lines.append("")
    lines.append("```")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
